// Códigos ISO 3166-1 alfa-2; los nombres se generan en español con Intl
const CODES =
  'AF AL DE AD AO AI AG AQ SA DZ AR AM AW AU AT AZ BS BH BD BB BE BZ BJ BM BY BO BA BW BR BN BG BF BI BT CV KH CM CA BQ QA TD CZ CL CN CY VA CO KM CG CD KP KR CI CR HR CU CW DK DM EC EG SV AE ER SK SI ES US EE SZ ET PH FI FJ FR GA GM GE GH GI GD GR GL GP GU GT GF GG GN GQ GW GY HT HN HK HU IN ID IQ IR IE BV IM CX NF IS KY CC CK FO GS HM FK MP MH UM PN SB TC VG VI IL IT JM JP JE JO KZ KE KG KI XK KW LA LS LV LB LR LY LI LT LU MO MK MG MY MW MV ML MT MA MQ MU MR YT MX FM MD MC MN ME MS MZ MM NA NR NP NI NE NG NU NO NC NZ OM NL PK PW PS PA PG PY PE PF PL PT PR GB CF DO RE RW RO RU EH WS AS BL KN SM MF PM VC SH LC ST SN RS SC SL SG SX SY SO LK ZA SD SS SE CH SR SJ TH TW TZ TJ IO TF TL TG TK TO TT TN TM TR TV UA UG UY UZ VU VE VN WF YE DJ ZM ZW'.split(' ');

const names = new Intl.DisplayNames(['es'], { type: 'region' });

export const COUNTRIES = [...new Set(CODES.map((c) => names.of(c)))].sort((a, b) =>
  a.localeCompare(b, 'es')
);
